### ISSUE TITLE
Throw error if hash attribute is not present

### ISSUE THREAD

**Issue by rianby64** [m3co/router3#43]
We should define if

```html
<div class="mdl-router3"></div> equals to <div class="mdl-router3" hash=""></div>
```

Theoretically they look equal...

**Comment by Anomeon** [comment]
I agree

**Comment by rianby64** [comment]
So, we should NOT to throw an error, but just leave ```hash``` to be ```''```, right?

**Comment by rianby64** [comment]
An offline talk gave us a light about this issue. And, let's throw anyway an error, and append and empty ```hash=""```

**Comment by rianby64** [comment]
@Anomeon in the example above, I suggest write [that test-case](https://github.com/m3co/router3/issues/43#issue-205520223) and throw an error anyway.

**Comment by Anomeon** [comment]
@rianby64 I have some progress. Need your review.
